### PR TITLE
Old array elements are removed from binding

### LINKED ISSUE #283: Deleting a element in an array of references removes the last entry instead
If the document that is being bound to state variable has a field that is an array of other document references and if those references are not being bound, then that field is returned as an array of strings containing paths to those documents. If any one of the reference in that array is removed from firebase console then vuexfire removes the last value in that array irrespective of the actual reference removed from database.

### PR DESCRIPTION
**Pull request by trickstival**
Fixes #283 

I'm still confused about how this works, but it does pass the test.

Basically, when updating an array I discard all the old values that are no longer in the new document and pass it as the "oldDoc" to the recursive `extractRefs`.

It passed all the tests, but I don't know if it breaks anything untested, which is pretty hard to predict.

I also changed the `extractRefs` function to use `for in` instead of `reduce` and added 2 new variables
for the result indexes instead of accessing them manually every time

### CODE REVIEW

**Comment by glumb** [comment]
Actually when updating to any version >2.0.0 that contains this fix I get the following error
```
TypeError: oldArray.filter is not a function
```
I'm passing a doc reference like so:
```js
await this.$bind('company', fb.collection('Companies').doc(await currentCompanyID), { reset: false })
```
works fine in 2.0.0

**Comment by posva** [comment]
@glumb can you boil down a repro and open an issue?
